

#ifdef BOARD_TASUP1TOUCHBE_V0003 

#define HARDWARE_NAME "TAS-UP1-Touch-BE V00.03"

#define OKNXHW_UP1_CONTROLLER2040
#include "OpenKNXHardware.h"

#define LED_DATA 18

#define TOUCH0_SCL 17
#define TOUCH0_SDA 16
#define TOUCH1_SCL 23
#define TOUCH1_SDA 22
#define TOUCHx_INT 19

#define THPCHANNEL_A_PWR 13
#define THPCHANNEL_A_SCL 15
#define THPCHANNEL_A_SDA 14

#define BINARY_INPUT_A 29
#define BINARY_INPUT_B 28
#define BINARY_INPUT_C 27
#define BINARY_INPUT_D 26
#define BINARY_INPUT_E 25
#define BINARY_INPUT_F 24
#define BINARY_INPUT_G 21
#define BINARY_INPUT_H 20



#endif